---
flags:
  model_rebuild: false
  dataset_rebuild: false
  params_update: false
path:
  config_dir: ./config
  data_dir_train: null
  data_dir_test: null
  pos_dir_train: [./data/train/positives/3band]
  neg_dir_train: [./data/train/negatives/neg/3band, ./data/train/negatives/LRGs/3band]
  train_csv: null
  pos_dir_test: [./data/test/positives/3band]
  neg_dir_test: [./data/test/negatives/3band]
  test_csv: null
  data_dir_pred: [./data/test/test_real]
  pred_csv: null
  pred_output_dir: ./result/pred
  pred_output_type: file
  test_output_dir: ./result/csv
  plot_output_dir: ./result/fig
  weights_dir: ./weights
  checkpoint_dir: ./checkpoints
  log_dir: ./logs
data:
  input_channels: 3
  image_size: 96
  num_workers: 10
  num_samples: null
  num_val_samples: 8000
  augment_mode: full
  color_jitter: false
  add_noise: false
  adaptation_mode: padding
  channel_expansion_mode: null
  mix_channels: false
  csv_samples_catalog_reader: sample
  norm: false
  update_mean_std: false
  mean: null
  std: null
train:
  optimizer: AdamW
  loss_function: BCEWithLogitsLoss
  scheduler:
    class: CosineAnnealingLR
    T_max: 30
    eta_min: 1.0e-11
    warmup_enabled: true
    warmup_steps: 10
  learning_rate: 0.0005
  batch_size: 128
  num_epochs: 1000
  weight_decay: 1.0e-05
  save_interval: 1
  self_evaluate_interval: 5
  process_bar:
    enabled: true
    train:
      colour: red
      desc: Training
    evaluate:
      colour: blue
      desc: Evaluating
    self-evaluate:
      colour: yellow
      desc: Self-evaluating
model:
  model_name: '# add model here'
  model_params: '# add model parameters here'
